### ISSUE TITLE
Running ROS2 navigation example results in multiple issues

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/RobotVacuumSample#10]
**Describe the bug**
Running ROS2 navigation example results in 3 issues:

 * Asset processor fails to process multiple assets.
 * RViz window lacking a map.
 * Segmentation fault (core dumped) errors.

All issues occur only on one machine.

Please note that the issue should be considered a Major.

**Steps to reproduce**
1. Set up O3DE. (https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/)
2. Set up RobotVacumSample. (https://github.com/o3de/RobotVacuumSample)
3. Attempt to process all Assets in the project (./AssetProcessor –project-path=~/Builds/RobotVacuumSample)
4. Launch the Editor. (./Editor)
5. Open the Loft Level and run the game.
6. Run RViz. (ros2 launch navigation.launch.py)

**Expected behavior**
No errors occur when running the project.

**Actual behavior**
Issues mentioned in the description are present.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/86951905/212921332-6ebdd43f-bf7f-4d3e-a025-9a297769c8c0.png)
![image](https://user-images.githubusercontent.com/86951905/212921363-af1a7752-40a3-490b-942a-4962f8cdb4f3.png)
![image](https://user-images.githubusercontent.com/86951905/212921386-7c82c6ce-2f90-4b52-9375-dca4371451f2.png)

**Found in Branch**
Development (50441b0)
o3de/RobotVacuumSample (main) ([58bc195](https://github.com/o3de/RobotVacuumSample/commit/58bc195b8dbfd4da7fe4213ee69404dd741fc2f3))

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository
50441b0**

**Desktop/Device:**
- Device: PC
- OS: Ubuntu
- Version 20.04
- CPU Intel i7-11700F
- GPU Nvidia GeForce RTX 3070
- Memory 32GB

**Additional context**
[specs.zip](https://github.com/o3de/RobotVacuumSample/files/10435859/specs.zip)

**Comment by hultonha** [comment]
@LB-RostyslavGavryliuk - could you include any more info about this issue? As this is only reported to occur on one machine could this be a local configuration problem? Maybe it might be worth reviewing the setup instructions here - https://github.com/o3de/o3de.org/pull/2191 to see if you can get unblocked and resolve the issue? Thanks!

**Comment by hultonha** [comment]
Thanks for following-up @LB-RostyslavGavryliuk! That's great to hear, much appreciated :+1:
