### ISSUE TITLE
Docker build fails with 'control_toolbox/pid.hpp' file not found

### ISSUE THREAD

**Issue by julesbelansolidstateofmind** [o3de/RobotVacuumSample#24]
While building the Docker I keep running into:
```
#0 1967.8 /data/workspace/o3de-extras/Gems/ROS2/Code/Include/ROS2/VehicleDynamics/DriveModels/PidConfiguration.h:11:10: #fatal error: 'control_toolbox/pid.hpp' file not found
#0 1967.8 #include <control_toolbox/pid.hpp>

```

Does anyone have any idea how to fix this, I already followed [this thread](https://answers.ros.org/question/34479/simple-question-about-include-control_toolboxpidh/) to no avail. I've also tried the obvious solution to `RUN apt install` the control_toolbox earlier in the script.

**Comment by adamdbrw** [comment]
This is fixed in both stable and development branch of ROS 2 Gem.
