### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by ulkesh11** [o3de/RobotVacuumSample#32]
I have followed the Setup instructions in the readme file but getting the following error while building this project
`cmake --build build/linux --config profile --target RobotVacuumSample Editor AssetProcessor -j 4

[1/1247] Building CXX object o3de/Code/Frame...amework.dir/profile/Unity/unity_16_cxx.cxx.o
FAILED: o3de/Code/Framework/AzFramework/CMakeFiles/AzFramework.dir/profile/Unity/unity_16_cxx.cxx.o 
/bin/g++ -DAZ_BUILD_CONFIGURATION_TYPE=\"profile\" -DAZ_ENABLE_DEBUG_TOOLS -DAZ_ENABLE_TRACING -DAZ_PROFILE_BUILD -DLINUX -DLINUX64 -DNDEBUG -D_FORTIFY_SOURCE=2 -D_HAS_EXCEPTIONS=0 -D_PROFILE -D__linux__ -DCMAKE_INTDIR=\"profile\" -I/home/simulator/test_ws/o3de/o3de/Code/Framework/AzFramework/. -I/home/simulator/test_ws/o3de/o3de/Code/Framework/AzFramework/Platform/Linux -I/home/simulator/test_ws/o3de/o3de/Code/Framework/AzFramework/Platform/Common -I/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/. -I/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/Platform/Linux -I/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/Platform/Common -I/home/simulator/test_ws/o3de/o3de/Code/Framework/AzNetworking/. -I/home/simulator/test_ws/o3de/o3de/Code/Framework/AzNetworking/Platform/Common -I/home/simulator/test_ws/o3de/o3de/Code/Framework/AzNetworking/Platform/Linux -I/home/simulator/test_ws/o3de/RobotVacuumSample/build/linux/o3de/Code/Framework/AzNetworking/Azcg/Generated/AzNetworking -isystem /home/simulator/.o3de/3rdParty/packages/Lua-5.4.4-rev1-linux/Lua/include -isystem /home/simulator/.o3de/3rdParty/packages/RapidJSON-1.1.0-rev1-multiplatform/RapidJSON/include -isystem /home/simulator/.o3de/3rdParty/packages/RapidXML-1.13-rev1-multiplatform/RapidXML/include -isystem /home/simulator/.o3de/3rdParty/packages/zlib-1.2.11-rev5-linux/zlib/include -isystem /home/simulator/.o3de/3rdParty/packages/cityhash-1.1-multiplatform/cityhash/src -isystem /home/simulator/.o3de/3rdParty/packages/lz4-1.9.4-rev2-linux/lz4/include -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -fpie -fstack-protector-all -Wno-array-bounds -Wno-attributes -Wno-class-memaccess -Wno-delete-non-virtual-dtor -Wno-enum-compare -Wno-format-overflow -Wno-format-truncation -Wno-int-in-bool-context -Wno-logical-not-parentheses -Wno-memset-elt-size -Wno-nonnull-compare -Wno-parentheses -Wno-reorder -Wno-restrict -Wno-sequence-point -Wno-sign-compare -Wno-strict-aliasing -Wno-stringop-overflow -Wno-stringop-truncation -Wno-switch -Wno-uninitialized -Wno-unused-result -msse4.1  -O2 -g -fPIC -std=c++17 -MD -MT o3de/Code/Framework/AzFramework/CMakeFiles/AzFramework.dir/profile/Unity/unity_16_cxx.cxx.o -MF o3de/Code/Framework/AzFramework/CMakeFiles/AzFramework.dir/profile/Unity/unity_16_cxx.cxx.o.d -o o3de/Code/Framework/AzFramework/CMakeFiles/AzFramework.dir/profile/Unity/unity_16_cxx.cxx.o -c /home/simulator/test_ws/o3de/RobotVacuumSample/build/linux/o3de/Code/Framework/AzFramework/CMakeFiles/AzFramework.dir/Unity/unity_16_cxx.cxx
In file included from /home/simulator/test_ws/o3de/RobotVacuumSample/build/linux/o3de/Code/Framework/AzFramework/CMakeFiles/AzFramework.dir/Unity/unity_16_cxx.cxx:11:
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzFramework/AzFramework/Quality/QualityCVarGroup.cpp: In instantiation of ‘AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)> [with auto:30 = AZ::SettingsRegistryInterface::VisitArgs]’:
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/typetraits/invoke_traits.h:206:95:   required by substitution of ‘template<class Fn, class ... Args> constexpr decltype (forward<Fn>(f)((forward<Args>)(AZStd::Internal::INVOKE::args)...)) AZStd::Internal::INVOKE(Fn&&, Args&& ...) [with Fn = AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>&; Args = {const AZ::SettingsRegistryInterface::VisitArgs&}]’
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/typetraits/invoke_traits.h:215:57:   required by substitution of ‘template<class Func, class ... Args> static decltype (AZStd::Internal::INVOKE(declval<Func>(), (declval<Args>)()...)) AZStd::Internal::invocable_r<void, AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>&, const AZ::SettingsRegistryInterface::VisitArgs&>::try_call<Func, Args ...>(int) [with Func = AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>&; Args = {const AZ::SettingsRegistryInterface::VisitArgs&}]’
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/typetraits/invoke_traits.h:219:67:   required from ‘struct AZStd::Internal::invocable_r<void, AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>&, const AZ::SettingsRegistryInterface::VisitArgs&>’
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/function/invoke.h:44:12:   required from ‘struct AZStd::invoke_result<AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>&, const AZ::SettingsRegistryInterface::VisitArgs&>’
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/function/invoke.h:49:11:   required by substitution of ‘template<class Fn, class ... ArgTypes> using invoke_result_t = typename AZStd::invoke_result::type [with Fn = AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>&; ArgTypes = {const AZ::SettingsRegistryInterface::VisitArgs&}]’
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/function/invoke.h:52:50:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/function/function_template.h:172:63:   required from ‘static R AZStd::Internal::function_util::get_invoker<R(Args ...), AZStd::Internal::function_util::function_obj_tag, AZStd::allocator>::call(AZStd::Internal::function_util::function_buffer&, Args&& ...) [with FunctionObj = AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>; R = AZ::SettingsRegistryInterface::VisitResponse; Args = {const AZ::SettingsRegistryInterface::VisitArgs&}]’
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/function/function_template.h:156:26:   required from ‘static AZStd::Internal::function_util::basic_vtable<R, Args ...> AZStd::Internal::function_util::get_invoker<R(Args ...), AZStd::Internal::function_util::function_obj_tag, AZStd::allocator>::create_vtable() [with FunctionObj = AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>; R = AZ::SettingsRegistryInterface::VisitResponse; Args = {const AZ::SettingsRegistryInterface::VisitArgs&}]’
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/function/function_template.h:538:101:   required from ‘void AZStd::function_intermediate<R, Args>::assign_to(Functor&&) [with Functor = AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>&; R = AZ::SettingsRegistryInterface::VisitResponse; Args = {const AZ::SettingsRegistryInterface::VisitArgs&}]’
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/function/function_template.h:405:28:   required from ‘AZStd::function_intermediate<R, Args>::function_intermediate(Functor&&, std::enable_if_t<((! std::is_integral<InputIterator>::value) && (! std::is_same<typename AZStd::remove_cvref<P>::type, AZStd::function_intermediate<R, Args> >::value)), int>) [with Functor = AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>&; R = AZ::SettingsRegistryInterface::VisitResponse; Args = {const AZ::SettingsRegistryInterface::VisitArgs&}; std::enable_if_t<((! std::is_integral<InputIterator>::value) && (! std::is_same<typename AZStd::remove_cvref<P>::type, AZStd::function_intermediate<R, Args> >::value)), int> = int; typename AZStd::remove_cvref<P>::type = AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>]’
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzCore/./AzCore/std/function/function_template.h:629:51:   required from ‘AZStd::function<R(Args ...)>::function(Functor&&, std::enable_if_t<((! std::is_integral<InputIterator>::value) && (! std::is_same<typename AZStd::remove_cvref<P>::type, AZStd::function<R(Args ...)> >::value)), int>) [with Functor = AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>&; R = AZ::SettingsRegistryInterface::VisitResponse; Args = {const AZ::SettingsRegistryInterface::VisitArgs&}; std::enable_if_t<((! std::is_integral<InputIterator>::value) && (! std::is_same<typename AZStd::remove_cvref<P>::type, AZStd::function<R(Args ...)> >::value)), int> = int; typename AZStd::remove_cvref<P>::type = AzFramework::QualityCVarGroup::LoadQualityLevel(AzFramework::QualityLevelNamespace::QualityLevel)::<lambda(const auto:30&)>]’
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzFramework/AzFramework/Quality/QualityCVarGroup.cpp:230:54:   required from here
/home/simulator/test_ws/o3de/o3de/Code/Framework/AzFramework/AzFramework/Quality/QualityCVarGroup.cpp:218:84: error: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘AzFramework::QualityLevelNamespace::QualityLevel’ [-Werror=format=]
  218 |                     PerformConsoleCommand(command, FixedValueString::format("%.*s/%d",
      |                                                                                   ~^
      |                                                                                    |
      |                                                                                    int
  219 |                         AZ_STRING_ARG(visitArgs.m_jsonKeyPath), currentQualityLevel));
      |                                                                 ~~~~~~~~~~~~~~~~~~~ 
      |                                                                 |
      |                                                                 AzFramework::QualityLevelNamespace::QualityLevel
cc1plus: all warnings being treated as errors
[4/1247] Building CXX object o3de/Code/Frame...ramework.dir/profile/Unity/unity_8_cxx.cxx.o
ninja: build stopped: subcommand failed.`

**Comment by michalpelka** [comment]
@ulkesh11 did you have an opportunity to test it against stable release?

**Comment by michalpelka** [comment]
Agreed to update readmes to explicitly point to the main (stable) version.

**Comment by jhanca-robotecai** [comment]
The issue should be completely solved after #34 and #35 were merged. In case there are any questions or comments, the issue might be reopened.
