### ISSUE TITLE
rviz2 not loading map

### ISSUE THREAD

**Issue by Poorunga** [o3de/RobotVacuumSample#38]
I successfully builed the project by referring to the dockerfile(https://github.com/o3de/RobotVacuumSample/blob/main/Docker/Dockerfile) of this project.

I can run ./Editor normally, but there will be some warnings and errors in the Console([Editor_log.txt](https://github.com/o3de/RobotVacuumSample/files/14893835/Editor_log.txt)). But this will not affect Play Game:
![image](https://github.com/o3de/RobotVacuumSample/assets/43004096/3b44e27e-55a0-49f3-a660-3654ebfb1396)

**I can't see the rviz2 map when I execute the `ros2 launch navigation.launch.py` command:**
![image](https://github.com/o3de/RobotVacuumSample/assets/43004096/23d1e394-b3f7-4d12-969c-bcbd1e9c7667)

This is the log after executing `ros2 launch navigation.launch.py` command ([ros2_launch_log.txt](https://github.com/o3de/RobotVacuumSample/files/14893852/ros2_launch_log.txt)). You can see many error messages like:
```
[planner_server-5] [INFO] [1712413326.269794621] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[async_slam_toolbox_node-1] [INFO] [1712413326.327493912] [slam_toolbox]: Message Filter dropping message: frame 'lidar' at time 798.576 for reason 'discarding message because the queue is full'
[async_slam_toolbox_node-1] [INFO] [1712413326.443101535] [slam_toolbox]: Message Filter dropping message: frame 'lidar' at time 798.691 for reason 'discarding message because the queue is full'
[async_slam_toolbox_node-1] [INFO] [1712413326.554221231] [slam_toolbox]: Message Filter dropping message: frame 'lidar' at time 798.807 for reason 'discarding message because the queue is full'
[async_slam_toolbox_node-1] [INFO] [1712413326.667794600] [slam_toolbox]: Message Filter dropping message: frame 'lidar' at time 798.918 for reason 'discarding message because the queue is full'
[pointcloud_to_laserscan_node-2] [WARN] [1712413326.700376530] [pc_to_laserscan]: New subscription discovered on topic '/scan', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
```

More information:
1. rviz2 has an error report about map:
![image](https://github.com/o3de/RobotVacuumSample/assets/43004096/2c958c02-5d55-482e-a9e8-3e3916b01be7)

2. I can only see the lidar sensor, not the imu. The video in your README.md（ O3DE_Consumer_Robotics_Demo.mp4） has imu.

**Comment by Poorunga** [comment]
This project seems to be just one step away from being ready to run, and we really need your help. @michalpelka @hultonha

**Comment by michalpelka** [comment]
Hello @Poorunga , which flavor of O3DE did you use? Development or main branch?
We test every minor release of O3DE against the environment. Please make sure :
- that you used **main** branch of o3de
- that you used **main** branch of o3de-extras
We are using `RMW_IMPLEMENTATION=rmw_cyclonedds_cpp` as DDS.

**Comment by michalpelka** [comment]
Correct me if I am wrong, but you recreate docker file in your environment and see no frames published by simulator.

**Comment by Poorunga** [comment]
@michalpelka Thank you very much for your answer. I referred to the dockerfile(https://github.com/o3de/RobotVacuumSample/blob/main/Docker/Dockerfile) for installation, but I did not use docker. Below is my installation script:
```
#!/bin/sh

# Collect the arguments for the base ros image
export ROS_VERSION=humble
export UBUNTU_VERSION=jammy

# Argument to determining the image type ('simulation' or 'navstack')
export IMAGE_TYPE=simulation  # Default to 'simulation'

# Arguments for the source repos needed for the robot vacuum sample docker
export O3DE_REPO=https://github.com/o3de/o3de.git
export O3DE_BRANCH=2310.1

export O3DE_EXTRAS_REPO=https://github.com/o3de/o3de-extras.git
export O3DE_EXTRAS_BRANCH=2310.1

export LOFT_GEM_REPO=https://github.com/o3de/loft-arch-vis-sample.git
export LOFT_GEM_BRANCH=main

export ROBOT_VAC_SAMPLE_REPO=https://github.com/o3de/RobotVacuumSample.git
export ROBOT_VAC_SAMPLE_BRANCH=main

# Additional argument to control build concurrency
export CMAKE_JOBS=8

export WORKSPACE=/data/workspace

mkdir -p $WORKSPACE

# Intall ros humble
apt install -y software-properties-common
add-apt-repository universe

apt update && sudo apt install curl -y
curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

apt update && apt install -y ros-humble-desktop
. /opt/ros/${ROS_VERSION}/setup.sh

# Add additional package repositories needed for packages
apt-get install -y --no-install-recommends gpg wget curl git git-lfs

#
# Install packages needed for cloning and building from the source repos
#

# Install the git and build tools
apt-get install -y --no-install-recommends \
	clang-14 \
	ninja-build \
	cmake \
	libglu1-mesa-dev \
	libxcb-xinerama0 \
	libxcb-xinput0 \
	libxcb-xinput-dev \
	libxcb-xfixes0-dev \
	libxcb-xkb-dev \
	libxkbcommon-dev \
	libxkbcommon-x11-dev \
	libfontconfig1-dev \
	libcurl4-openssl-dev \
	libsdl2-dev \
	zlib1g-dev \
	mesa-common-dev \
	libssl-dev libxcb-icccm4 \
	libxcb-image0 \
	libxcb-keysyms1 \
	libxcb-render-util0 \
	libxcb-randr0 \
	libnvidia-gl-470 \
	ufw \
	ros-${ROS_DISTRO}-slam-toolbox \
	ros-${ROS_DISTRO}-navigation2 \
	ros-${ROS_DISTRO}-nav2-bringup \
	ros-${ROS_DISTRO}-pointcloud-to-laserscan \
	ros-${ROS_DISTRO}-gazebo-msgs \
	ros-${ROS_DISTRO}-ackermann-msgs \
	ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
	ros-${ROS_DISTRO}-control-toolbox \
	ros-${ROS_DISTRO}-nav-msgs

# Clone O3DE repos, register, build, and cleanup in the same layer to reduce the size
if [ "${IMAGE_TYPE}" = "simulation" ]; then
	apt-get install -y --no-install-recommends ros-${ROS_DISTRO}-desktop
	cd $WORKSPACE
	git clone $O3DE_REPO
	git -C $WORKSPACE/o3de checkout $O3DE_BRANCH
	git -C $WORKSPACE/o3de lfs install
	git -C $WORKSPACE/o3de lfs pull
	$WORKSPACE/o3de/python/get_python.sh
	$WORKSPACE/o3de/scripts/o3de.sh register -ep $WORKSPACE/o3de
	git clone $O3DE_EXTRAS_REPO
	git -C $WORKSPACE/o3de-extras checkout $O3DE_EXTRAS_BRANCH
	$WORKSPACE/o3de/scripts/o3de.sh register -gp $WORKSPACE/o3de-extras/Gems/ROS2
	git clone $LOFT_GEM_REPO
	git -C $WORKSPACE/loft-arch-vis-sample checkout $LOFT_GEM_BRANCH
	git -C $WORKSPACE/loft-arch-vis-sample lfs install
	git -C $WORKSPACE/loft-arch-vis-sample lfs pull
	$WORKSPACE/o3de/scripts/o3de.sh register -gp $WORKSPACE/loft-arch-vis-sample/Gems/ArchVis/
	git clone $ROBOT_VAC_SAMPLE_REPO
	git -C $WORKSPACE/RobotVacuumSample checkout $ROBOT_VAC_SAMPLE_BRANCH
	git -C $WORKSPACE/RobotVacuumSample lfs install
	git -C $WORKSPACE/RobotVacuumSample lfs pull
	$WORKSPACE/o3de/scripts/o3de.sh register -pp $WORKSPACE/RobotVacuumSample/
	. /opt/ros/${ROS_DISTRO}/setup.sh
	cmake -B $WORKSPACE/RobotVacuumSample/build/linux -S $WORKSPACE/RobotVacuumSample -G "Ninja Multi-Config" -DLY_STRIP_DEBUG_SYMBOLS=TRUE -DLY_DISABLE_TEST_MODULES=ON
	cmake --build $WORKSPACE/RobotVacuumSample/build/linux --config profile --target AssetProcessorBatch RobotVacuumSample.GameLauncher RobotVacuumSample.Assets Editor -j $CMAKE_JOBS
elif [  "${IMAGE_TYPE}" = "navstack" ]; then
	apt-get install -y --no-install-recommends ros-${ROS_DISTRO}-desktop
	cd $WORKSPACE
	git clone --recursive $ROBOT_VAC_SAMPLE_REPO
	git -C $WORKSPACE/RobotVacuumSample checkout $ROBOT_VAC_SAMPLE_BRANCH
else
	echo "Unsupported IMAGE_TYPE: ${IMAGE_TYPE}" && exit 1
fi
```

> Q1:that you used main branch of o3de
> Q2:that you used main branch of o3de-extras

A1: 2310.1
A2: 2310.1

> We are using RMW_IMPLEMENTATION=rmw_cyclonedds_cpp as DDS.

How can I confirm this?

**Comment by michalpelka** [comment]
I've run the script on my end, and everything you have done seems ok.
The missing floor was probably due to asset processing done after the first run.
Please make sure that you have all assets processed by [asset processor](https://docs.o3de.org/docs/user-guide/assets/asset-processor/) before starting the game in the Editor 
![image](https://github.com/o3de/RobotVacuumSample/assets/3209244/d7328f1e-0e34-433c-a2d7-fe8bae53cd96)

It seems to me, that you forgot to launch Slam toolbox. To start navigating the robot I needed to run:
- run Editor and wait for asset processor to finish processing,
- start slam-toolbox : `ros2 launch RobotVacuumSample/launch/navigation.launch.py `
- start nav2 : `ros2 launch RobotVacuumSample/launch/navigation.launch.py `
![image](https://github.com/o3de/RobotVacuumSample/assets/3209244/9b4a06cb-55f9-4f53-a070-f2fc398564a5)

**Comment by Poorunga** [comment]
@michalpelka I really appreciate your willingness to run my script yourself, your suggestions have been very helpful. I try to confirm whether [asset processor](https://docs.o3de.org/docs/user-guide/assets/asset-processor/) is normal.

> start slam-toolbox : ros2 launch RobotVacuumSample/launch/navigation.launch.py 
start nav2 : ros2 launch RobotVacuumSample/launch/navigation.launch.py 

But, these two instructions(start slam-toolbox and nav2) are a bit confusing to me, they seem to be the same command(What you are talking about is different from README.md). And I have already executed this command.

**More information**
I can use `ros2 run teleop_twist_keyboard teleop_twist_keyboard` to control vacuum in O3DE editor by keyboard.

**Comment by michalpelka** [comment]
Sorry, you are right, `slam.launch.py` is included in `navigation.launch.py`.
I worked for me running only `ros2 launch RobotVacuumSample/launch/navigation.launch.py`.
Please verify if you have all nodes running after launching `ros2 launch RobotVacuumSample/launch/navigation.launch.py`:
```
/behavior_server
/bt_navigator
/bt_navigator_navigate_through_poses_rclcpp_node
/bt_navigator_navigate_to_pose_rclcpp_node
/controller_server
/global_costmap/global_costmap
/lifecycle_manager_navigation
/local_costmap/local_costmap
/o3de_ros2_node
/pc_to_laserscan
/planner_server
/slam
/slam_toolbox
/smoother_server
/transform_listener_impl_5982d880bce0
/transform_listener_impl_5bee612aae00
/transform_listener_impl_61a83a70b8a0
/transform_listener_impl_6244ec3ad620
/transform_listener_impl_7064540045b0
/transform_listener_impl_7c2728002ed0
/velocity_smoother
/waypoint_follower
```
It seems that SLAM toolbox does not publish transform from map to base_link.

**Comment by Poorunga** [comment]
I executed `ros2 node list` and it seems to be the same as yours:
![image](https://github.com/o3de/RobotVacuumSample/assets/43004096/47c6d07b-04f5-4433-86ae-f855d1bb18bc)

> It seems that SLAM toolbox does not publish transform from map to base_link.

How to confirm this?

**Comment by michalpelka** [comment]
Please run following:
```
ros2 run tf2_tools view_frames 
```
and put here resulted plot (frames.pdf):
![image](https://github.com/o3de/RobotVacuumSample/assets/3209244/76dc7552-ac84-490f-b434-f1a35b79296e)

**Comment by michalpelka** [comment]
Hello, @Poorunga did you manage to run those checks on tf frames?

**Comment by Poorunga** [comment]
@michalpelka Thanks for ping me. Sorry, I don't have time to verify as you suggested recently. But I should be able to finish it this week.

**Comment by Poorunga** [comment]
@michalpelka  It seems like some nodes are missing

![image](https://github.com/o3de/RobotVacuumSample/assets/43004096/6235ec58-a31f-4c97-b7cd-f8e5a8e36ef5)

**Comment by adamdbrw** [comment]
@Poorunga did you manage to debug the issue? If you still need help after trying, could you share ROS logs (as file) from when you start the navigation stack?

**Comment by Poorunga** [comment]
@michalpelka  Thank you help. 

> could you share ROS logs (as file) from when you start the navigation stack?

sure.

When running ros2 launch navigation.launch.py, the log printed on the console: [nav_launch.log](https://github.com/o3de/RobotVacuumSample/files/15011352/nav_launch.log)

ros logs in $HOME/.ros/log : [ros_log.tar.gz](https://github.com/o3de/RobotVacuumSample/files/15011457/ros_log.tar.gz)

**Comment by michalpelka** [comment]
It seems that one othe nodes is not happy with QoS.
```
1713359107.5526161 [pointcloud_to_laserscan_node-2] [WARN] [1713359107.552232213] [pc_to_laserscan]: New subscription discovered on topic '/scan', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
```
So the pointcloud_to_laser scan is not producing 2D laser scan for Nav2.
In working setup, I can see `/scan` valid messages in second instance of rviz2:
![image](https://github.com/o3de/RobotVacuumSample/assets/3209244/c7efde9a-9526-4ad1-9352-d39338b13f00)
It is likely a problem with the environment / dds. In the sim you can change QoS for every simulated sensor, so it can help to find a solution.
![image]
In screenshot below you can see change applied (Reliability policy):
(https://github.com/o3de/RobotVacuumSample/assets/3209244/33e23944-cfac-4b55-b726-92304758dbb8)

**Comment by Poorunga** [comment]
> In the sim you can change QoS for every simulated sensor, so it can help to find a solution.

According to the method you described, I should set Qos to be `reliable` every time?

> It is likely a problem with the environment / dds.

Is the cause of this problem my computer resources being too low?
