### ISSUE TITLE
README.md: Documentation lacks of commands

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/RobotVacuumSample#8]
**Describe the bug**
Launching the robot application docker image with the command provided (`sudo docker run --rm --network="bridge" --gpus all -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix -it o3de_robot_vacuum_navstack:latest /data/workspace/LaunchNavStack.bash
`) results in error, as build command (`sudo docker build -t o3de_robot_vacuum_simulation:latest .`) refers to building simulation and navstack together. While rest of the documentation shows run command when simulation and navstack was built separately. The mentioned error is:

```
Unable to find image 'o3de_robot_vacuum_simulation:latest' locally
docker: Error response from daemon: pull access denied for o3de_robot_vacuum_simulation, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
To run the robot application docker image the command has to be change to: 

`sudo docker run --rm --network="bridge" --gpus all -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix -it o3de_robot_vacuum_simulation:latest /data/workspace/LaunchNavStack.bash`

Please note that the issue should be considered a Major. 

**Steps to reproduce**
1. Go to https://github.com/o3de/RobotVacuumSample/blob/main/README.md
2. Follow the instruction (do not execute the optional command: `sudo docker build --build-arg IMAGE_TYPE=navstack -t o3de_robot_vacuum_navstack:latest .`

**Expected behavior**
Documentation provides proper commands for running the Docker Image.

**Actual behavior**
Documentation does not include commands for running the Docker Image when simulation and navstack were built together.

**Found in Branch**
main

**Commit ID from [o3de/RobotVacuumSample(https://github.com/o3de/RobotVacuumSample) Repository**
58bc195

**Desktop/Device:**

- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.3 LTS
- CPU: AMD Ryzen 5 3600 6-Core Processor
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

**Comment by spham-amzn** [comment]
This was fixed by https://github.com/o3de/RobotVacuumSample/pull/11

**Comment by hultonha** [comment]
> This was fixed by #11

Awesome thanks @spham-amzn! 🥳

**Comment by LB-MichalRodzos** [comment]
@spham-amzn @hultonha The description of the issue provides a wrong documentation link, which is a mistake I made while creating the ticket. For which I would like to apologize.

The proper documentation is here: https://github.com/o3de/RobotVacuumSample/tree/main/Docker

Do you want me to reopen this issue or create a new one? If you wish to leave the issue as it is, please let me know when the new Fix is merged and I will verify it, as the issue is still present in the Docker instruction.

**Comment by hultonha** [comment]
Could you please create a new issue with the updated info @LB-MichalRodzos and then tag me and @spham-amzn please. Thanks!
